version: '2'

services:
  docker-lap56-deb:
    build: .
    image: docker-lap56-deb:1.0
    container_name: docker-lap56-deb
    ports:
      - "8085:80"
      - "4435:443"
    restart: always
    volumes:
      - /home/helder/www:/var/www/html
