version: '2'

services:
  docker-lap72-deb:
    build: .
    image: docker-lap72-deb:1.0
    container_name: docker-lap72-deb
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /home/helder/www:/var/www/html
      - /home/helder/www/ssl:/etc/apache2/ssl
      - /home/helder/www/sites-enabled:/etc/apache2/sites-enabled
    extra_hosts:
      - "e-processo.local:127.0.0.1"
