version: '2'

services:
  docker-lap70-deb:
    build: .
    image: docker-lap70-deb:1.0
    container_name: docker-lap70-deb
    ports:
      - "8070:80"
      - "4437:443"
    restart: always
    volumes:
      - /home/helder/www:/var/www/html
